version: '3.8'
services:
  db:
    image: postgres:15
    container_name: nextjs-portfolio-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio
      TZ: "Asia/Tokyo"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: